### ISSUE TITLE
newbie question about start

### ISSUE THREAD

**Issue by emplant2000** [ahmad-aljabali/ROS-Blender-Addon#2]
I want to start ur add-on.
 [  START  ] or [ p] which is correct?

when i click [ START ] . it's to be roscore isnot running. 

https://www.facebook.com/groups/1351809401872109/posts/1609121629474217/
(jump to facebook)

**Comment by ahmad-aljabali** [comment]
Hi,
I'm not entirely sure what you mean by [p], regardless I assume you forgot to start the main ROS run time by typing:
`roscore`
in the terminal, if you have a screenshot I might be able to help more.

note that I've only tested this on Ubuntu so far.

**Comment by emplant2000** [comment]
[p] is execute python script on UPBGE :)

this screen-shot is with [p] on win10 is here as same as ubuntu 20.04LTS.
https://i.imgur.com/cSsRkVm.jpeg
![sample](https://i.imgur.com/cSsRkVm.jpeg "win10")

and pls check my facebook gruop 'blenderROSJP'

**Comment by ahmad-aljabali** [comment]
Okay, it's a UPBGE thing, honestly I haven't used it before so you're on your own for now at least if you have specific issues with error messages you can share then I might be able to help, you are testing on Windows and UPBGE which I didn't test on either so I'd expect you to need to modify the code slightly I'll be glad to help you understand any part of the code that isn't clear.

P.s: I saw your group unfortunately I don't understand Japanese, best of luck!

**Comment by emplant2000** [comment]
ok, running on ubuntu with roscore as well.
![image](https://user-images.githubusercontent.com/721686/161459263-5b8839d2-0a35-46ee-a007-da80d45e227c.png)
